apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-lanchonete-order-config
  labels:
    app: ms-lanchonete-order-config
data:
  MONGODB_URI: "mongodb://fiaplanchonete:rmontoza@lanchonete-order-docdb-cluster.cluster-c1428q0gijk9.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/010928185677/sql-lanchonete-checkout"